Convert launcher.fsx to a project
Line 260-265 in make.fsx is added because CI was throwing
the following error without copying fsx.runtimeconfig.json
to the fsx installation directory:

```
C:\Program Files\fsx\fsx.bat D:\a\fsx\fsx\scripts\runTests.fsx
Cannot use file stream for [C:\Program Files\fsx\fsx.deps.json]: No such file or directory
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\fsx\'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'C:\Program Files\fsx\fsx.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'C:\Program Files\fsx\fsx.runtimeconfig.json' file and specify the appropriate framework.
System.Exception: Tests failed
   at <StartupCode$FSI_0007>.$FSI_0007.main@() in D:\a\fsx\fsx\scripts\make.fsx:line 337
```