Fsdk.Tests: upgrade deps to fix build
Even though we don't depend on Newtonsoft.Json directly, I guess
transitive deps were:

```
Running unit tests...

dotnet test /home/runner/work/fsx/fsx/src/Fsdk.Tests/Fsdk.Tests.fsproj
  Determining projects to restore...
/home/runner/work/fsx/fsx/src/Fsdk.Tests/Fsdk.Tests.fsproj : error NU1903: Warning As Error: Package 'Newtonsoft.Json' 9.0.1 has a known high severity vulnerability, https://github.com/advisories/GHSA-5crp-9r3c-p9vr
  Restored /home/runner/work/fsx/fsx/src/Fsdk/Fsdk.fsproj (in 229 ms).
  Failed to restore /home/runner/work/fsx/fsx/src/Fsdk.Tests/Fsdk.Tests.fsproj (in 229 ms).
Error when running 'dotnet test /home/runner/work/fsx/fsx/src/Fsdk.Tests/Fsdk.Tests.fsproj'
FSI_0003.Fsdk.Process+ProcessFailed: ProcessFailed
  "Error when running 'dotnet test /home/runner/work/fsx/fsx/src/Fsdk.Tests/Fsdk.Tests.fsproj'"
   at FSI_0003.Fsdk.Process.ProcessResult.Unwrap(String errMsg) in /home/runner/work/fsx/fsx/src/Fsdk/Process.fs:line 139
   at FSI_0003.Fsdk.Process.ProcessResult.UnwrapDefault() in /home/runner/work/fsx/fsx/src/Fsdk/Process.fs:line 151
   at FSI_0006.RunUnitTests() in /home/runner/work/fsx/fsx/scripts/runUnitTests.fsx:line 135
   at <StartupCode$FSI_0006>.$FSI_0006.main@() in /home/runner/work/fsx/fsx/scripts/runUnitTests.fsx:line 140
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Stopped due to error
Error: Process completed with exit code 1.
```