One more LEGACY_FRAMEWORK wrapping to fix build
Otherwise we get warnings as errors that are kinda impossible to
fix today:
```
/home/runner/work/fsx/fsx/src/Fsdk/Network.fs(246,9):
error FS0044: This construct is deprecated. WebRequest,
HttpWebRequest, ServicePoint, and WebClient are obsolete.
Use HttpClient instead. Settings on ServicePointManager no
longer affect SslStream or HttpClient.
[/home/runner/work/fsx/fsx/src/fsx/fsx.fsproj]
```